### ISSUE TITLE
Plugin doesn't honor server.properties options or difficulty

### ISSUE THREAD

**Issue by ZizzyZizzy** [Nukkit-coders/MobPlugin#113]
### Info
Jul 21 15:56 [Server] INFO Loading MobPlugin v1.9.0.5
Jul 21 16:18 [Server] INFO This server is running Nukkit git-5be51b1 implementing API version 1.0.8 for Minecraft: BE v1.12.0 (protocol version 361)

This is:
- [X] bug report
- [X] feature request
- [ ] other

### Your issue / suggestion
Nukkit server.properties defaults to spawn-mobs=on, and spawn-animals=on, which of course does nothing right now.

However, MobPlugin doesn't honor either of those settings if they are disabled. Mobs and animals will spawn regardless.

Same for difficulty=peaceful. The monsters should no longer spawn and any that have already spawned should disappear immediately when changing difficulty.

Great work, otherwise! Survival mode is next to impossible (and boring) without mobs/animals for food and supplies. I particularly love how the mob spawners are working! Awesome!

**Comment by PetteriM1** [comment]
https://github.com/Nukkit-coders/MobPlugin/commit/0664267fb293bbfd838dd5c8c5c5b74a5bce2448 I made mobs to disappear on peaceful difficulty. That doesn't happen before server restart though because of the way how Nukkit currently handles difficulty. I also added a warning that server.properties settings doesn't affect to MobPlugin and made gamerule doMobSpawning work (+ other updates). If you want to change spawning settings, edit MobPlugin's config.yml file.
